lab:
    os: bionic
    os_raid1:
#        size: 512
        disk1: sda
        disk2: sdc
        os_partitions:
            /var: 20G
            /tmp: 14G
            /boot: 1G
            /: 60G
            /home: 20G
    net_bounding:
        slaves:
            - enp4s0f0
            - enp4s0f1
        name: bond0
        vlans:
            br-mgmt: 2126
            br-storage: 2128
    os_packages:
        - saltstack
